branches:
  only:
    - master
language: minimal
services:
  - docker
install: ./build/install.sh
script:
  - ./build/test.sh
  - ./build/build.sh
before_deploy:
  - >-
    docker run
    --env FIREBASE_APP
    --env FIREBASE_SECRET
    popcode
    yarn run gulp syncFirebase
deploy:
  - provider: s3
    access_key_id: AKIAYK4E7IUAJBMMWUNL
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: popcode.org
    skip_cleanup: true
    local-dir: dist
    acl: public_read
    on:
      repo: popcodeorg/popcode
      branch: master
  - provider: s3
    access_key_id: AKIAYK4E7IUAJBMMWUNL
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: popcode.school
    skip_cleanup: true
    local-dir: dist
    acl: public_read
    on:
      repo: popcodeorg/popcode
      branch: master
  - provider: script
    script: >-
      echo "$DOCKER_PASSWORD" |
      docker login -u "$DOCKER_USERNAME" --password-stdin &&
      docker tag popcode popcodeorg/popcode &&
      docker push popcodeorg/popcode
    on:
      repo: popcodeorg/popcode
      branch: master

after_deploy:
  - >
    docker run
    --env CLOUDFLARE_EMAIL
    --env CLOUDFLARE_KEY
    --env CLOUDFLARE_ZONE
    --env HOSTNAME
    popcode
    yarn run gulp purgeCache
notifications:
  slack:
    secure: IJ0LSnahbfPFMFFgEK+wwSYEUWjJ2AFZz89oSmzSuKqEchM7AA2tpkCAPvN37cUksPE4YozVXxx++SQ4j+fk1lmhhddEUYO9ueB/UqD3iu0xCFR/CJ30ka7QDkfzkatKkn0H8MVU3FwEJ6ZbHJR2zJVUALPFw7AQ08EE4GpTC2TfWSiYuv1AnuVUC8ZkvGBjwFN1lQrAnHFS62sreNmYtBR0FHHo9DEE+NanYdtLnFYyGeDauWx7I1ERT1vnv4G+0vx5Guu7TGwC1uzHCTlciqSGPeaifaC+uXR/8VaTabZS4G1PsR8ROYt3S/RFtCEAfuhBvlcWdNnfLH7/xLhET4W35H/hhHmSaMYJCy/gnQW/bXfLCxtO5/luwM5nOM4NeQcRybqreBL/q4K78giw6ttpTo5EumBxXrYKo4PRWfOWkOhePotQ/IRzpsoMqFHxzlJxv9HPSnFb+11OTe3BsxfWpsHs233eIBpKYOcjpzXPP4GSq7FH2V7jL2lg6Cc81XUK2v8upJpPoWRRfM52LxemNi+uEMBrgLro6VA2O5qRDN/+mhr8wYS4dLms5uk6Hq87UA9xhlIUl0P9d6kfN0vHi+QzxLMLvA1ateFncaG7MKTgMNjsckziKlR2B8FZ1c3lT55RB/zfojGzrDs0l7TCKB+WKP5uPJEWw5/UC2A=
